@baseAddress = http://localhost:5098

GET {{baseAddress}}/api/categories
Accept: application/json

###

POST {{baseAddress}}/api/categories
Accept: application/json

###
GET {{baseAddress}}/api/categories/test
Accept: application/json