<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseMicroservice.Shared\CourseMicroservice.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\files\excel\" />
    <Folder Include="wwwroot\files\image\" />
    <Folder Include="wwwroot\files\other\" />
    <Folder Include="wwwroot\files\pdf\" />
    <Folder Include="wwwroot\files\word\" />
  </ItemGroup>

</Project>
